name: Backfill rates

on:
  workflow_dispatch:
    inputs:
      start:
        description: "Start date (YYYY-MM-DD)"
        required: true
        default: "2024-01-01"
      end:
        description: "End date (YYYY-MM-DD)"
        required: true
        default: "2024-12-31"
      currencies:
        description: "Comma-separated list of ISO (blank = all)"
        required: false
        default: "USD,EUR,RUB"

jobs:
  backfill:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - name: Run backfill
        run: python scripts/backfill.py "${{ inputs.start }}" "${{ inputs.end }}" "${{ inputs.currencies }}"
      - name: Commit & push
        run: |
          git config user.name "rates-bot"
          git config user.email "rates-bot@users.noreply.github.com"
          git add -A
          git commit -m "chore: backfill ${{ inputs.start }}..${{ inputs.end }}" || echo "No changes"
          git push
